---
title: "Get participant infection windows"
output: html_notebook
---

## Figure out how long ago Fonville 2016 participants could have been infected

```{r}
source('analysis_funs.R')
library(lubridate)
sampling_dates = read_csv('../raw_data/sampling_dates_Dataset_S1.csv', skip = 1, show_col_types = F) %>%
  select(1:4) %>%
  separate(`sample selection interval`, into = c('sample_start', 'sample_end'), sep = '-') %>%
  mutate(across(starts_with('sample'), ~lubridate::as_date(.x, format = '%d/%m/%Y')))

participants = import_human_titer_data() %>%
  merge(sampling_dates, by = 'season') %>%
  select(subject, age_mos, season, starts_with('sample')) %>%
  mutate(earliest_dob = ymd(sample_start) - months(age_mos),
         latest_dob = ymd(sample_end) - months(age_mos)) %>%
  distinct()
```

## Get a vector of all sampling dates
```{r}
sample_dates_sequence <- function(start, end){
  seq(ymd(start), ymd(end), by = 'days')
}

all_sample_dates <- with(sampling_dates %>% 
       filter(!is.na(sample_start)),
  mapply(FUN = sample_dates_sequence, start = sample_start, end = sample_end)
) %>%
  unlist() %>%
  as_date()
```


```{r}
get_epidemic_dates_for_pariticipant <- function(participant_row,
                                                all_sample_dates){
  merge(participant_row,
        tibble(subject = participant_row$subject, 
               epidemic_dates_in_lifetime = all_sample_dates[all_sample_dates %in%
                                                               seq(ymd(participant_row$earliest_dob), ymd(participant_row$sample_end), by = 'days')]),
        by = 'subject')
}
```

## Expand the participants data frame to include a row for each date that occured during their lifetime
```{r}
full_df = lapply(1:nrow(participants), function(rr){
  get_epidemic_dates_for_pariticipant(slice(participants, rr), all_sample_dates)
}) %>% 
  bind_rows() %>%
  group_by(subject) %>%
  mutate(earliest_infection_date = min(epidemic_dates_in_lifetime), 
         max_lag = sample_end - earliest_infection_date,
         n_seasons = sum( c(NA, epidemic_dates_in_lifetime[-1]-epidemic_dates_in_lifetime[-n()]) > 30, na.rm = T)+1)
full_df
```

## Plot
```{r}
full_df %>%
  ggplot() +
  geom_point(aes(x = epidemic_dates_in_lifetime, y = subject), color = 'red', size = 1)+
  geom_segment(aes(x = earliest_dob, xend = sample_end, y = subject, yend = subject), lty = 3) +
  geom_segment(aes(x = earliest_dob, xend = latest_dob, y = subject, yend = subject)) +
  geom_segment(aes(x = sample_start, xend = sample_end, y = subject, yend = subject)) +
  geom_text(aes(x = sample_end + 200, y = subject, label = max_lag))
ggsave('../plots/epidemic_dates_by_participant.png', height = 4, width = 9, units = 'in', dpi = 200)
```


## Save a .csv with pariticpant dates and lags
```{r}
full_df %>%
  select(subject, sample_start, sample_end, earliest_dob, latest_dob, earliest_infection_date, max_lag, n_seasons) %>%
write_csv(file = '../processed_data/subject_primary_sample_timing.csv')
```

```{r}
full_df %>%
  group_by(subject, max_lag, n_seasons) %>%
  summarise()
```





